import "./globals.scss";
import Footer from "../app/components/Footer";
export const metadata = {
  title: "Sobha Hartland",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
